os: osx
osx_image: xcode12.2
before_install:
- brew update
- touch $HOME/sum.sha256
- echo "0f910a98c138ac70edec7058647b3e7f247db4a080bf262e0fb3d7528ed99483 *$HOME/AIRSDK_Compiler.dmg"
  >> $HOME/sum.sha256
- echo "17fda7ac8d3e476cad3127f345455ef316acfb87c6f4322e5897bd8d9b09388e *$HOME/apache-flex-sdk-4.16.1-bin.tar.gz"
  >> $HOME/sum.sha256
- wget -P $HOME https://archive.apache.org/dist/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz
- wget -P $HOME https://airdownload.adobe.com/air/mac/download/32.0/AIRSDK_Compiler.dmg
- shasum -a 256 --check $HOME/sum.sha256
- tar xzf $HOME/apache-flex-sdk-4.16.1-bin.tar.gz
- mv apache-flex-sdk-4.16.1-bin $HOME/
- hdiutil mount $HOME/AIRSDK_Compiler.dmg
- ditto /Volumes/AIR\ SDK/ $HOME/apache-flex-sdk-4.16.1-bin/
- export PATH=$HOME/apache-flex-sdk-4.16.1-bin/bin:$PATH
install:
- echo "do nothing"
before_script:
- echo "do nothing"
script:
- echo "do nothing"
before_deploy:
- mkdir build
- TAG_VERSION=${TRAVIS_TAG%%-*}
- FILENAME=NNDD_${TAG_VERSION//./_}
- wget -P ./build https://github.com/SSW-SCIENTIFIC/NNDD/releases/download/$TRAVIS_TAG/${FILENAME}.air
- ls -al build/
- adt -package -target native $(pwd)/build/${FILENAME}.dmg $(pwd)/build/${FILENAME}.air
deploy:
  provider: releases
  api_key:
    secure: "lS9kj0xC+XwD3NQK1EhBU0xI+fpReYb9nXgiEocCKEan5YVGkg+c6trumMb6LvqOsUDrzC3hYCK+U4he9oeAL7wHJSdQBcX1VDDWQ7oOzeadkwli5OxN1RtQk4aLnjxOJH3N8HYM+blI6zJ7BdgUcRF3SUclD6fIlTXiyntQZ8BRZubA0oMSn/c+VSAtdKQFS09mHj1DxHYgk4OYUWC8+BIIDPScwcWX/Aen4ENxE8oBg1Roscn2JAUzpvyHekzpNeg2BRP8sjd6y+8sroNmfBXVEKmbz1fp1ZwWq1rV5VKvsG4mPjNnlCZAvAizOgUE+dQZG0iBIJPYYtPQA08hshTTjuQJESNJCpy2NmWkVzyfkyCnkUg511gi1d+mr/xIkqv33rZAOU56ph4/2RFW3yQKUaWWHW3IXdgf4Etfgh7K5tzYPizc8lgVf0P6iGfp3qp1eEraj9U3TP3cBXryXxYmx30yX/lGDmBGQzaKQoyjrEdkaPvi3cwuCXu7WqcC2mxjGcRXRVRScGCvM4NJmKjzTJhe4oQW4ZlymwFh+1lk2Dbw3JvMmst0jjM+25vE9rV9bukf1/hOUa+NqnGFyOaz201xrcLNcG03f+oL0jh8StqNsqsXE+ah5Q9gA9PFvEZrQrCW53CqXOSFArCmDruZhUZU54pw9DaljOCyCEA="
  file: build/${FILENAME}.dmg
  skip_cleanup: true
  on:
   tags: true 
