name: build
on:
  push:
    branches:
      - master
jobs:
  build-air:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup
        run: |
          curl https://dlcdn.apache.org/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz -O
          curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O
          curl https://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw -o osmf.swc
          tar xzf apache-flex-sdk-4.16.1-bin.tar.gz
          mv apache-flex-sdk-4.16.1-bin /opt/flex
          unzip AdobeAIRSDK.zip -d /opt/flex
          mv osmf.swc /opt/flex/frameworks/libs/

      - name: build
        env:
          certificate_password: ${{ secrets.NNDD_5CH_CERTIFICATE_PASSWORD }}
          AIR_HOME: /opt/flex
        run: |
          cd src
          /opt/flex/bin/amxmlc NNDD.mxml -compiler.include-libraries ../libs/* -warnings=false
          java -jar /opt/flex/lib/adt.jar -package -storetype pkcs12 -keystore ../nndd-5ch_certificate.pfx -storepass $certificate_password NNDD.air NNDD-app.xml NNDD.swf icon32.png icon128.png icon48.png icon16.png CategoryList.json

      - uses: actions/upload-artifact@v2
        with:
          name: air
          path: src/NNDD.air

  build-exe:
    needs: build-air
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: air

      - name: setup
        shell: bash
        run: |
          curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O
          unzip AdobeAIRSDK.zip -d air

      - name: build
        run: |
          air/bin/adt.bat -package -target native NNDD.exe NNDD.air

      - uses: actions/upload-artifact@v2
        with:
          name: exe
          path: NNDD.exe

  build-dmg:
    needs: build-air
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: air

      - name: setup
        run: |
          curl https://airdownload.adobe.com/air/mac/download/32.0/AdobeAIRSDK.dmg -O
          hdiutil mount AdobeAIRSDK.dmg
          ditto '/Volumes/AIR SDK' air

      - name: build
        run: |
          air/bin/adt -package -target native NNDD.dmg NNDD.air

      - uses: actions/upload-artifact@v2
        with:
          name: dmg
          path: NNDD.dmg
