name: build
on:
  push:
    branches:
      - master
    paths:
      - libs/**
      - src/**
      - nicovideo4as
jobs:
  build-air:
    runs-on: ubuntu-latest
    env:
      AIR_HOME: /opt/airsdk
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup
        run: |
          curl https://dlcdn.apache.org/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz -O
          curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O
          curl https://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw -o osmf.swc
          tar xzf apache-flex-sdk-4.16.1-bin.tar.gz
          mv apache-flex-sdk-4.16.1-bin $AIR_HOME
          unzip AdobeAIRSDK.zip -d $AIR_HOME
          mv osmf.swc $AIR_HOME/frameworks/libs/

      - name: category list update
        run: |
          (cd utils/category_list_update && npm ci)
          utils/category_list_update/node_modules/.bin/ts-node utils/category_list_update/fetch_ranking_genre_tags.ts > src/CategoryList.json

      - name: build
        run: |
          cd src
          $AIR_HOME/bin/amxmlc NNDD.mxml -compiler.include-libraries ../libs/* -warnings=false
          java -jar $AIR_HOME/lib/adt.jar -certificate -cn SelfSigned 2048-RSA certificate_no_password.pfx ''
          java -jar $AIR_HOME/lib/adt.jar -package -storetype pkcs12 -keystore certificate_no_password.pfx -storepass '' NNDD.air NNDD-app.xml NNDD.swf icon32.png icon128.png icon48.png icon16.png CategoryList.json

      - uses: actions/upload-artifact@v3
        with:
          name: air
          path: src/NNDD.air

  build-exe:
    needs: build-air
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: air

      - name: setup
        shell: bash
        run: |
          curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O
          unzip AdobeAIRSDK.zip -d air

      - name: build
        run: |
          air/bin/adt.bat -package -target native NNDD.exe NNDD.air

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: NNDD.exe

  build-dmg:
    needs: build-air
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: air

      - name: setup
        run: |
          curl https://airdownload.adobe.com/air/mac/download/32.0/AdobeAIRSDK.dmg -O
          hdiutil mount AdobeAIRSDK.dmg
          ditto '/Volumes/AIR SDK' air

      - name: build
        run: |
          air/bin/adt -package -target native NNDD.dmg NNDD.air

      - uses: actions/upload-artifact@v3
        with:
          name: dmg
          path: NNDD.dmg
