name: build
on:
  push:
    branches:
      - master
    paths:
      - libs/**
      - src/**
      - nicovideo4as
  workflow_dispatch:
jobs:
  build-air:
    runs-on: ubuntu-latest
    env:
      AIR_HOME: /opt/airsdk
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache@v4
        id: apache_flex_cache
        with:
          path: apache-flex-sdk-4.16.1-bin.tar.gz
          key: https://dlcdn.apache.org/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz
      - if: steps.apache_flex_cache.outputs.cache-hit != 'true'
        run: curl https://dlcdn.apache.org/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz -O

      - uses: actions/cache@v4
        id: adobe_airsdk_cache
        with:
          path: AdobeAIRSDK.zip
          key: http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip
          enableCrossOsArchive: true
      - if: steps.adobe_airsdk_cache.outputs.cache-hit != 'true'
        run: curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O

      - uses: actions/cache@v4
        id: flex_osmf20_cache
        with:
          path: OSMF2_0.swc
          key: https://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw
      - if: steps.flex_osmf20_cache.outputs.cache-hit != 'true'
        run: curl https://sourceforge.net/adobe/flexsdk/code/HEAD/tree/trunk/frameworks/libs/OSMF2_0.swc?format=raw -o OSMF2_0.swc

      - name: setup
        run: |
          tar xzf apache-flex-sdk-4.16.1-bin.tar.gz
          mv apache-flex-sdk-4.16.1-bin $AIR_HOME
          unzip AdobeAIRSDK.zip -d $AIR_HOME
          cp OSMF2_0.swc $AIR_HOME/frameworks/libs/osmf.swc

      - name: build
        run: |
          cd src
          $AIR_HOME/bin/amxmlc NNDD.mxml -compiler.include-libraries ../libs/* -warnings=false
          java -jar $AIR_HOME/lib/adt.jar -certificate -cn SelfSigned 2048-RSA certificate_no_password.pfx ''
          java -jar $AIR_HOME/lib/adt.jar -package -storetype pkcs12 -keystore certificate_no_password.pfx -storepass '' NNDD.air NNDD-app.xml NNDD.swf icon32.png icon128.png icon48.png icon16.png CategoryList.json

      - uses: actions/upload-artifact@v4
        with:
          name: air
          path: src/NNDD.air

  build-exe:
    needs: build-air
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: air

      - uses: actions/cache@v4
        id: adobe_airsdk_cache
        with:
          path: AdobeAIRSDK.zip
          key: http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip
          enableCrossOsArchive: true
      - if: steps.adobe_airsdk_cache.outputs.cache-hit != 'true'
        run: curl http://fpdownload.macromedia.com/air/win/download/32.0/AdobeAIRSDK.zip -O

      - name: setup
        shell: bash
        run: |
          unzip AdobeAIRSDK.zip -d air

      - name: build
        run: |
          air/bin/adt.bat -package -target native NNDD.exe NNDD.air

      - uses: actions/upload-artifact@v4
        with:
          name: exe
          path: NNDD.exe

  build-dmg:
    needs: build-air
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: air

      - uses: actions/cache@v4
        id: adobe_airsdk_cache
        with:
          path: AdobeAIRSDK.dmg
          key: https://airdownload.adobe.com/air/mac/download/32.0/AdobeAIRSDK.dmg
      - if: steps.adobe_airsdk_cache.outputs.cache-hit != 'true'
        run: curl https://airdownload.adobe.com/air/mac/download/32.0/AdobeAIRSDK.dmg -O

      - name: setup
        run: |
          hdiutil mount AdobeAIRSDK.dmg
          ditto '/Volumes/AIR SDK' air

      - name: build
        run: |
          air/bin/adt -package -target native NNDD.dmg NNDD.air

      - uses: actions/upload-artifact@v4
        with:
          name: dmg
          path: NNDD.dmg
